# 应用的名称
spring:
  application:
    name: cluster-ribbon-hystrix-turbine-amqp

# 服务的端口
server:
  port: 20018

# 注册中心的集群地址
eureka:
  client:
    service-url:
      defaultZone: http://msrainbow-server-master:2222/eureka/,http://msrainbow-server-slave-one:3333/eureka/
  instance:
    prefer-ip-address: true
    non-secure-port: 20018

management:
  port: 30018

# trubine的配置
#turbine:
#  app-config: cluster-ribbon-consumer-service-amqp
  # 如果不配置这里，则监控的url需要为：host:port/turbine.stream?cluster=CUSTOMERS
#  cluster-name-expression: new String("default")
#  combine-host-port: true
#  stream:
#    port: 20019
