spring:
  application:
    name: ms-rainbow-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YuJhon/ms-rainbow-config-server-center
          username: YuJhon
          password: jiangyu1321
server:
  port: 40002